export const ADMIN_LOADING_START = 'ADMIN_LOADING_START';
export const ADMIN_SIGNUP_SUCCESS = 'ADMIN_SIGNUP_SUCCESS';
export const ADMIN_SIGNUP_FAILED = 'ADMIN_SIGNUP_FAILED';
export const ADMIN_AUTH_SUCCESS = 'ADMIN_AUTH_SUCCESS';
export const ADMIN_AUTH_FAILED = 'ADMIN_AUTH_FAILED';
export const ADMIN_AUTH_LOGOUT = 'ADMIN_AUTH_LOGOUT';
export const ADMIN_LOGOUT_FAILED = 'ADMIN_LOGOUT_FAILED';

export const QUESTIONS_LOADING_START = 'QUESTIONS_LOADING_START';
export const EDIT_QUESTIONS_SUCCESS = 'EDIT_QUESTIONS_SUCCESS';
export const EDIT_QUESTIONS_FAILED = 'EDIT_QUESTIONS_FAILED';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const GET_QUESTIONS_FAILED = 'GET_QUESTIONS_FAILED';
