/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:ecc17fee-104a-46dc-bff9-903700f4b188",
    "aws_cognito_region": "ap-south-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "8b6cc0a291104abb91f5ae59f4b7691d",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
